data = [
    {
        "Question": "What would you consider your greatest strength?",
        "Answers": [
            {
                "text": "Courage and bravery",
                "score_G": 10,
                "score_S": 3,
                "score_H": 5,
                "score_R": 2,
            },
            {
                "text": "Intelligence and wisdom",
                "score_G": 2,
                "score_S": 3,
                "score_H": 2,
                "score_R": 10,
            },
            {
                "text": "Kindness and loyalty",
                "score_G": 5,
                "score_S": 2,
                "score_H": 10,
                "score_R": 3,
            },
            {
                "text": "Ambition and resourcefulness",
                "score_G": 3,
                "score_S": 10,
                "score_H": 2,
                "score_R": 5,
            },
        ],
    },
    {
        "Question": "In a group project, what role do you usually take on?",
        "Answers": [
            {
                "text": "The leader, guiding the team to success",
                "score_G": 10,
                "score_S": 8,
                "score_H": 5,
                "score_R": 5,
            },
            {
                "text": "The researcher, finding all the necessary information",
                "score_G": 2,
                "score_S": 5,
                "score_H": 3,
                "score_R": 10,
            },
            {
                "text": "The helper, making sure everyone has what they need",
                "score_G": 3,
                "score_S": 2,
                "score_H": 10,
                "score_R": 4,
            },
            {
                "text": "The strategist, coming up with a plan to maximize results",
                "score_G": 5,
                "score_S": 10,
                "score_H": 4,
                "score_R": 8,
            },
        ],
    },
    {
        "Question": "What is your biggest pet peeve?",
        "Answers": [
            {
                "text": "People giving up too easily",
                "score_G": 10,
                "score_S": 5,
                "score_H": 4,
                "score_R": 5,
            },
            {
                "text": "Ignorance or lack of curiosity",
                "score_G": 4,
                "score_S": 5,
                "score_H": 4,
                "score_R": 10,
            },
            {
                "text": "Selfishness or unkindness",
                "score_G": 5,
                "score_S": 2,
                "score_H": 10,
                "score_R": 4,
            },
            {
                "text": "Laziness or lack of ambition",
                "score_G": 5,
                "score_S": 10,
                "score_H": 4,
                "score_R": 5,
            },
        ],
    },
    {
        "Question": "If you encountered a magical creature in danger, what would you do?",
        "Answers": [
            {
                "text": "Rush to its aid without a second thought",
                "score_G": 10,
                "score_S": 3,
                "score_H": 8,
                "score_R": 2,
            },
            {
                "text": "Carefully assess the situation and decide how to help",
                "score_G": 5,
                "score_S": 3,
                "score_H": 4,
                "score_R": 10,
            },
            {
                "text": "Comfort the creature and find a safe way to assist",
                "score_G": 3,
                "score_S": 2,
                "score_H": 10,
                "score_R": 5,
            },
            {
                "text": "Consider if helping could provide any valuable rewards",
                "score_G": 2,
                "score_S": 10,
                "score_H": 3,
                "score_R": 5,
            },
        ],
    },
    {
        "Question": "Which subject at Hogwarts would be your favorite?",
        "Answers": [
            {
                "text": "Defense Against the Dark Arts",
                "score_G": 10,
                "score_S": 5,
                "score_H": 4,
                "score_R": 2,
            },
            {
                "text": "Potions or Arithmancy",
                "score_G": 3,
                "score_S": 10,
                "score_H": 2,
                "score_R": 10,
            },
            {
                "text": "Herbology or Care of Magical Creatures",
                "score_G": 4,
                "score_S": 3,
                "score_H": 10,
                "score_R": 5,
            },
            {
                "text": "Charms or Transfiguration",
                "score_G": 5,
                "score_S": 4,
                "score_H": 3,
                "score_R": 10,
            },
        ],
    },
    {
        "Question": "Which magical artifact would you choose?",
        "Answers": [
            {
                "text": "The Sword of Gryffindor - it appears when you need it most",
                "score_G": 10,
                "score_S": 3,
                "score_H": 5,
                "score_R": 2,
            },
            {
                "text": "The Diadem of Ravenclaw - it enhances wisdom",
                "score_G": 3,
                "score_S": 2,
                "score_H": 2,
                "score_R": 10,
            },
            {
                "text": "The Hufflepuff Cup - it symbolizes loyalty and kindness",
                "score_G": 4,
                "score_S": 3,
                "score_H": 10,
                "score_R": 3,
            },
            {
                "text": "The Slytherin Locket - a mark of ambition and legacy",
                "score_G": 2,
                "score_S": 10,
                "score_H": 3,
                "score_R": 5,
            },
        ],
    },
    {
        "Question": "What do you value most in a friendship?",
        "Answers": [
            {
                "text": "Trust and loyalty through thick and thin",
                "score_G": 8,
                "score_S": 3,
                "score_H": 10,
                "score_R": 2,
            },
            {
                "text": "Intellectual connection and stimulating conversations",
                "score_G": 3,
                "score_S": 2,
                "score_H": 3,
                "score_R": 10,
            },
            {
                "text": "Compassion and kindness, always being there for each other",
                "score_G": 5,
                "score_S": 2,
                "score_H": 10,
                "score_R": 3,
            },
            {
                "text": "Shared goals and support in achieving ambitions",
                "score_G": 2,
                "score_S": 10,
                "score_H": 4,
                "score_R": 5,
            },
        ],
    },
    {
        "Question": "How would you react if you discovered a hidden magical talent?",
        "Answers": [
            {
                "text": "Use it to help those around you and make the world better",
                "score_G": 8,
                "score_S": 3,
                "score_H": 10,
                "score_R": 3,
            },
            {
                "text": "Study and perfect it to understand its power",
                "score_G": 3,
                "score_S": 5,
                "score_H": 3,
                "score_R": 10,
            },
            {
                "text": "Keep it safe and only use it for good purposes",
                "score_G": 5,
                "score_S": 2,
                "score_H": 10,
                "score_R": 4,
            },
            {
                "text": "Explore its potential and use it to further your goals",
                "score_G": 3,
                "score_S": 10,
                "score_H": 2,
                "score_R": 5,
            },
        ],
    },
    {
        "Question": "Choose a favorite magical creature:",
        "Answers": [
            {
                "text": "Hippogriff - courageous and respects bravery",
                "score_G": 10,
                "score_S": 3,
                "score_H": 4,
                "score_R": 2,
            },
            {
                "text": "Phoenix - wise, with incredible healing powers",
                "score_G": 3,
                "score_S": 4,
                "score_H": 4,
                "score_R": 10,
            },
            {
                "text": "Niffler - kind-hearted and loyal",
                "score_G": 4,
                "score_S": 3,
                "score_H": 10,
                "score_R": 3,
            },
            {
                "text": "Basilisk - powerful and ambitious",
                "score_G": 2,
                "score_S": 10,
                "score_H": 3,
                "score_R": 5,
            },
        ],
    },
    {
        "Question": "What would you see in the Mirror of Erised?",
        "Answers": [
            {
                "text": "Leading a life of adventure and courage",
                "score_G": 10,
                "score_S": 3,
                "score_H": 4,
                "score_R": 2,
            },
            {
                "text": "Achieving greatness in knowledge and understanding",
                "score_G": 3,
                "score_S": 4,
                "score_H": 3,
                "score_R": 10,
            },
            {
                "text": "Building strong connections and a happy, peaceful life",
                "score_G": 4,
                "score_S": 2,
                "score_H": 10,
                "score_R": 4,
            },
            {
                "text": "Reaching the peak of success and recognition",
                "score_G": 3,
                "score_S": 10,
                "score_H": 2,
                "score_R": 5,
            },
        ],
    },
]
